//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiversityReports.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EEOSurvey
    {
        public int EEOSurveyID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string Gender { get; set; }
        public Nullable<int> EthnicityID { get; set; }
        public Nullable<bool> USMilitary { get; set; }
        public Nullable<bool> LGBT { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> EnteredByAdmin { get; set; }
        public Nullable<int> VisuallyIdentifyAdmin { get; set; }
        public string EEO1Category { get; set; }
    }
}
