//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiversityReports.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmployeeID { get; set; }
        public string EmployeeIDEncrypted { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Gender { get; set; }
        public string StreetAddress { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string HomeEmail { get; set; }
        public string HomeFax { get; set; }
        public string HomePhone { get; set; }
        public string HomePhone2 { get; set; }
        public string PersonalWireless { get; set; }
        public string PersonalPager { get; set; }
        public string SecondaryAddress { get; set; }
        public string SecondaryCity { get; set; }
        public string SecondaryState { get; set; }
        public string SecondaryZip { get; set; }
        public string SecondaryPhone { get; set; }
        public string SpouseOrPartner { get; set; }
        public string ConfidentialAddress { get; set; }
        public string ForeignLanguageSpoken { get; set; }
        public Nullable<int> JobTitle { get; set; }
        public Nullable<int> Department { get; set; }
        public string Location { get; set; }
        public string WorkPhone { get; set; }
        public string WorkFax { get; set; }
        public string WorkEmail { get; set; }
        public string RoomNumber { get; set; }
        public Nullable<System.DateTime> HireDate { get; set; }
        public Nullable<System.DateTime> TerminationDate { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<decimal> BillingRate { get; set; }
        public string PreferredName { get; set; }
        public string MiddleInitial { get; set; }
        public string PreferredLastName { get; set; }
        public string PreferredFirstName { get; set; }
        public string PreferredMiddleName { get; set; }
        public Nullable<bool> IsListPreferredNameFirst { get; set; }
        public string TechnologyActive { get; set; }
        public string StatusType { get; set; }
        public string ClassYear { get; set; }
        public string TreatedAsYear { get; set; }
        public Nullable<int> EEOCategory_ID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
